#!/home/david/ansible/myansible/bin/ansible-playbook

- name: AltSchool Ansible Project
  hosts: aws_ec2
  become: true
  become_user: root
  vars:
    path: "/var/www/html"


  tasks:
    - block:
      - name: Set Server to the Africa/Lagos Timezone, Update Packages and Display Timezone
        command: "{{ item }}"
        with_items:
          - timedatectl set-timezone Africa/Lagos
          - timedatectl
          - apt update -y 
        register: checkZone
      - debug: var=checkZone.results[1].stdout_lines[3].lstrip()

      - name: Install Apache2 on Server
        apt:
          name: apache2
          state: present

      - name: Install PHP on Server
        apt:
          name: php
          state: present

      - name: "Delete PHP Index File if Present"
        ansible.builtin.file:
          path: "{{ path }}/index.php"
          state: absent

      - name: Copy PHP Index File
        copy:
          src: /home/david/Desktop/Terra/ansible/index.php
          dest: "{{ path }}"     
          mode: 0644
        notify:
          - Stop Apache Service
          - Start Apache Service
        
      - name: Check Apache2 Status
        shell: systemctl status apache2
        register: ApacheStatus
      - debug: var=ApacheStatus.stdout_lines[2].lstrip()

  handlers:
    - name: Stop Apache Service
      service:
        name: apache2
        state: stopped

    - name: Start Apache Service
      service:
        name: apache2
        state: started